---
detectors:
  Attribute:
    enabled: false
  NilCheck:
    enabled: false
  DuplicateMethodCall:
    max_calls: 2
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    accept:
    - V1

exclude_paths:
  - tmp
  - spec
  - vendor
  - log
  - coverage
  - config
  - bin
  - db/migrate
