APP_HOST: 'publicv.localhost'
APP_PORT: '3000'

# Mail
MAIL_FROM: 'example@reply.com'
MAILGUN_API_KEY: 'api key'
MAILGUN_DOMAIN: 'domain'
MAIL_REPLY_TO: 'example@reply.com'

# Secrets
DEVISE_PEPPER: 'rails secret'
DEVISE_SECRET_KEY: 'rails secret'
SECRET_KEY_BASE: 'rails secret'

LOCATIONIQ_API_KEY: 'locationiq api key'
LOCATIONIQ_PUBLIC_KEY: 'locationiq public key'
